Add Grand Winner
fossasia/codeheat.org pull request #296
Opened 2020-12-11 15:24 UTC by daretobedifferent18

Issue #295

2020-12-11 15:34 UTC, mariobehling commented
Please provide a color headshot image instead of a very dark image.

2020-12-11 16:23 UTC, Raunaksingh100 reviewed
It is very great you can add all the winners and Finalist of this 1 coding contents in this pr...

You will get images from the GitHub profile.

2020-12-11 16:42 UTC, daretobedifferent18 commented
@mariobehling Should I add all the winners or just mine?

2020-12-11 17:35 UTC, Raunaksingh100 commented
> @mariobehling Should I add all the winners or just mine?

You can add all the winners and grand prize winner see in the issue there is need of all not the one..

2020-12-12 09:55 UTC, mariobehling commented
Each winner can make their own PR. You only need to resolve merge conflicts later if they appear, but that should not be too difficult for you guys.

2020-12-13 18:43 UTC, sachinchauhan2889 requested changes
Divyam i have copied your code from this PR. while editing your code into my pr I found these. you can apply these changes to your PR also.

2020-12-13 18:43 UTC, sachinchauhan2889 commented on index.html
> +				<div class="row">
closing tag if this div i.e </div> not present.

2020-12-13 18:43 UTC, sachinchauhan2889 commented on index.html
> +			<div class="container">
closing tag if this div i.e not present.

2020-12-13 18:43 UTC, sachinchauhan2889 commented on index.html
> +	</section>
have wrong identation.

2020-12-13 18:43 UTC, sachinchauhan2889 commented on index.html
> +						<h1>Grand Winners</h1>
Grand Prize Winnners

2020-12-13 18:48 UTC, sachinchauhan2889 commented
you can also remove left padding of h1 containing "grand prize winning" because picture and text are are perfectly aligned.

2020-12-15 20:14 UTC, daretobedifferent18 commented
@mariobehling I don't have any other pic right now. Could you accept this one only

2021-01-01 06:25 UTC, iamareebjamal commented
@daretobedifferent18 Please update

2021-01-01 13:10 UTC, daretobedifferent18 commented
@iamareebjamal Done

2021-01-01 14:48 UTC, merged