chore: add Naman Kalra as finalist winner.
fossasia/codeheat.org pull request #342
Opened 2021-06-27 13:12 UTC by Naman-1234

Please find the screenshot here:
![Screenshot (98)](https://user-images.githubusercontent.com/63748249/123545762-73dee680-d777-11eb-943a-96d6abe7de54.png)

2021-06-27 13:35 UTC, iamdevvalecha approved these changes

2021-06-27 13:35 UTC, iamdevvalecha commented
@mariobehling

2021-06-29 13:08 UTC, mariobehling requested changes
This image is too big. 2.2 MB is way to big. Please reduce image size.

2021-06-30 04:43 UTC, Naman-1234 commented
@mariobehling  Sir I have reduced the image size. Could you please take a look now. Thanks.

2021-07-05 23:14 UTC, merged